create table public.challenge_steps (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  challenge_id uuid null,
  sequence smallint null,
  title text null,
  instructions text null,
  reflection_questions text[] null,
  updated_at timestamp with time zone null,
  constraint challenge_steps_pkey primary key (id),
  constraint challenge_steps_challenge_id_fkey foreign KEY (challenge_id) references challenges (id)
) TABLESPACE pg_default;