create table public.challenges (
  id uuid not null default extensions.uuid_generate_v4 (),
  content_meta_id uuid null,
  program_id uuid null,
  title text not null,
  subtitle text null,
  pub_date timestamp with time zone not null,
  updated_date timestamp with time zone null,
  description text null,
  sequence integer null,
  is_open boolean null default false,
  difficulty text null,
  badges jsonb null,
  cover_image jsonb null,
  language text not null default 'en'::text,
  version integer null,
  archived boolean null default false,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null,
  milestone_id uuid null,
  tags text[] null,
  constraint challenges_pkey primary key (id),
  constraint challenges_content_meta_id_fkey foreign KEY (content_meta_id) references content_meta (id),
  constraint challenges_milestone_id_fkey foreign KEY (milestone_id) references content_meta (id),
  constraint challenges_program_id_fkey foreign KEY (program_id) references programs (id)
) TABLESPACE pg_default;