create table public.events (
  id uuid not null default gen_random_uuid (),
  title text not null,
  description text null,
  event_type text not null,
  event_format text not null,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone not null,
  online_link text null,
  is_paid boolean not null default false,
  is_member_only boolean not null default false,
  price numeric(10, 2) null,
  currency text null default 'USD'::text,
  capacity integer null,
  featured_image_url text null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  created_by uuid not null,
  location jsonb null,
  sessions jsonb[] null,
  exhibits jsonb[] null,
  constraint events_pkey primary key (id),
  constraint events_created_by_fkey foreign KEY (created_by) references auth.users (id)
) TABLESPACE pg_default;