create table public.resource_meta (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null,
  slug text null,
  title text null,
  created_by uuid null default auth.uid (),
  status text null,
  tags text[] null,
  categories text[] null,
  description text null,
  constraint resource_meta_pkey primary key (id),
  constraint resource_meta_created_by_fkey foreign KEY (created_by) references auth.users (id)
) TABLESPACE pg_default;