create table public.discounts (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  code text not null,
  entity_name text null,
  entity_type text not null,
  entity_id uuid not null,
  valid_from timestamp without time zone null,
  valid_until timestamp without time zone null,
  value numeric not null,
  value_type text not null,
  currency text null,
  updated_at timestamp with time zone null,
  constraint discounts_pkey primary key (id)
) TABLESPACE pg_default;