create table public.offerings (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  description text null,
  entity_type text null,
  related_entity_id uuid null default gen_random_uuid (),
  base_price_amount numeric null,
  currency text null,
  duration_months smallint null,
  is_active boolean null,
  updated_at timestamp with time zone null default now(),
  name text not null,
  constraint offerings_pkey primary key (id)
) TABLESPACE pg_default;