create table public.user_transactions (
  id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone not null default now(),
  base_amount numeric null,
  currency text null,
  discount_amount numeric null,
  discount_id bigint null,
  offering_id bigint null,
  offering_name text null,
  offering_type text null,
  payment_method text null,
  payment_provider text null,
  provider_data jsonb null,
  provider_transaction_id text null,
  status text null,
  tax_amount numeric null,
  total_amount_paid numeric null,
  updated_at timestamp with time zone null,
  user_id uuid null default auth.uid (),
  constraint user_transactions_pkey primary key (id),
  constraint user_transactions_discount_id_fkey foreign KEY (discount_id) references discounts (id),
  constraint user_transactions_offering_id_fkey foreign KEY (offering_id) references offerings (id),
  constraint user_transactions_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;