create table public.user_question_responses (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  content text null,
  updated_at timestamp with time zone null,
  user_id uuid null,
  feedback_rating smallint null,
  question_id bigint null,
  constraint user_question_pkey primary key (id),
  constraint user_question_responses_question_id_fkey foreign KEY (question_id) references user_questions (id),
  constraint user_question_responses_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;