create table public.user_challenge_progress (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid null,
  email text null,
  challenge_id uuid not null,
  updated_at timestamp with time zone null,
  completed_at timestamp with time zone null,
  last_step_completed smallint null,
  reflections jsonb[] null,
  feedback_rating smallint null,
  notification_sent jsonb null,
  feedback_text text null,
  constraint user_challenge_progress_pkey primary key (id),
  constraint user_challenge_progress_challenge_id_fkey foreign KEY (challenge_id) references challenges (id),
  constraint user_challenge_progress_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;