create table public.user_bookmarks (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid null,
  content_type text null,
  related_content_id uuid null,
  reference_url text null,
  reference_table text null,
  constraint user_bookmarks_pkey primary key (id),
  constraint user_bookmarks_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;