create table public.user_enrollments (
  id bigint generated by default as identity not null,
  enrolled_at timestamp with time zone not null default now(),
  user_id uuid null default gen_random_uuid (),
  program_id uuid null default gen_random_uuid (),
  program_name text null,
  transaction_id uuid null default gen_random_uuid (),
  constraint program_enrollments_pkey primary key (id),
  constraint program_enrollments_program_id_fkey foreign KEY (program_id) references programs (id),
  constraint program_enrollments_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;