create table public.user_questions (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  title text null,
  content text null,
  user_id uuid null,
  related_content_id uuid null,
  reference_url text null,
  is_public boolean null,
  status text null,
  content_type text null,
  reference_table text null,
  constraint users_questions_pkey primary key (id),
  constraint users_questions_user_id_fkey foreign KEY (user_id) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;