create table public.user_accomplishments (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid null default gen_random_uuid (),
  accomplishment_id bigint null,
  earned_at timestamp with time zone null,
  context_data jsonb null,
  constraint user_accomplishments_pkey primary key (id),
  constraint user_accomplishments_accomplishment_id_fkey foreign KEY (accomplishment_id) references accomplishments (id),
  constraint user_accomplishments_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;