create table public.user_notes (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  title text null,
  related_content_id uuid null,
  content_type text null,
  user_id uuid not null default auth.uid (),
  updated_at timestamp with time zone null,
  content text null,
  reference_url text null,
  reference_table text null,
  constraint notes_pkey primary key (id),
  constraint notes_created_by_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;